name: Build and Push Docker Image

on:
  push:
    paths:
      - 'server/**'
    branches: [ "main" ]

jobs:

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Login to DockerHub
      id: login-docker-hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: setup-docker-buildx
      uses: docker/setup-buildx-action@v3.11.1

    - name: Build for Trivy Scan
      id: build-for-trivy
      uses: docker/build-push-action@v6
      with:
        context: ./server
        load: true
        cache-from: type:gha
        cache-to: type=gha,mode=max
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/brevly-server:scan

    - name: Run Trivy vulnerability scanner
      id: trivy-scan
      uses: aquasecurity/trivy-action@0.33.1
      with:
        image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/brevly-server:scan'
        format: 'table'
        # exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Build and Push Docker Image
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        context: ./server
        push: true
        cache-from: type:gha
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/brevly-server:latest
